config/routes.rb
Rails.application.routes.draw do
  root to: 'memos#index'
  resources :memos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :content, length: { maximum: 140}
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

  def index
    @memos = Memo.all
  end

  def new
    @memo = Memo.new
  end

  def create
    memo = Memo.new(memo_params)
    memo.save!
    redirect_to memos_path, notice: "メモを登録しました"
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    memo = Memo.find(params[:id])
    memo.update!(memo_params)
    redirect_to memos_path, notice: 'メモを更新しました'
  end

  def destroy
    memo = Memo.find(params[:id])
    memo.delete
    redirect_to memos_path
  end

  def show
    @memo = Memo.find(params[:id])
  end


  private

  def memo_params
    params.require(:memo).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="haku">
      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/edit.html.erb
<h1>メモの編集</h1>

<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>注意！！</strong> メモの内容は140文字を越えると、更新されません！
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= form_with model: @memo do |form|%>
  <div class="form-group">
    <%= form.label :title, 'タイトル'%>
    <p><%= form.text_field :title, class: 'form-control'%></p>
  </div>
  <div class="form-group">
    <%= form.label :content, '内容'%>
    <p><%= form.text_area :content, class: 'form-control'%></p>
  </div>
  <div class="text-center">
    <%= form.submit '更新する', class: 'btn btn-primary'%>
  </div>
<% end %>

 <%= link_to '一覧へ', memos_path %>

app/views/memos/index.html.erb
<h1>メモ一覧</h1>
<%= link_to '新しく投稿する', new_memo_path, class: 'btn btn-success'%>

<% @memos.each do |memo| %>

  <div class="card top" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= memo.title %></h5>
      <p class="card-text fontc"><%= memo.content %></p>
      <%= link_to '編集', edit_memo_path(memo.id) %>
      <%= link_to '削除', memo_path(memo.id), method: :delete %>
      <%= link_to '詳細', memo_path(memo.id) %>
    </div>
  </div>

<% end %>

app/views/memos/new.html.erb
<h1>新しくメモを作成</h1>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>注意！！</strong> メモの内容は140文字を越えると、保存されません！
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<%= form_with model: @memo do |form|%>
  <div class="form-group">
    <%= form.label :title, 'タイトル'%>
    <p><%= form.text_field :title, class: 'form-control'%></p>
  </div>
  <div class="form-group">
    <%= form.label :content, '内容'%>
    <p><%= form.text_area :content, class: 'form-control'%></p>
  </div>
  <div class="text-center">
    <%= form.submit '登録する', class: 'btn btn-primary'%>
  </div>
<% end %>
 <%= link_to '一覧へ', memos_path %>

app/views/memos/show.html.erb
<h1>メモの詳細</h1>
  <div class="haba">
    <p>title⤵︎<h3><%= @memo.title %></h3></p>
    <p>content⤵︎<h5 class="fontc"><%= @memo.content %></h5></p>
  </div>
<%= link_to '一覧へ', memos_path %>